### ISSUE TITLE
Need CFN Yaml to switch TimeStream

### ISSUE THREAD

**Issue by byongwu** [aws-solutions/machine-to-cloud-connectivity-framework#15]
**Is your feature request related to a problem? Please describe.**

Some regions like Seoul (ap-northeast-2) does not support AWS TimeStream, yet CFN (CloudFormation) Yaml created by this CDK has hard wired TimeStream creation and example using it.

**Describe the feature you'd like**

I would like M2C2 CDK or M2C2 CFN Yaml to have a control switch (CFN radio box?) to disable TimeStream and examples for regions not supporting TimeStream.

**Additional context**

Originally requested by AWS internal Slack channel.

**Comment by fhoueto-amz** [comment]
Hi Byong-Wu
We have discussed this and unfortunately  are not planning  to implement this enhancement. You may fork the code and add the change. Based on that I am closing this ticket. 
Thanks
Fabien
