### ISSUE TITLE
Pyro3 is no longer being maintained !!!

### ISSUE THREAD

**Issue by wchaws** [aws-solutions/machine-to-cloud-connectivity-framework#2]
https://github.com/irmen/Pyro3 is no longer being maintained. The official doc suggest using Pyro4

https://github.com/awslabs/machine-to-cloud-connectivity-framework/blob/5daf5f750bfa1d95cc3200476bd3230cb0df2c2a/source/machine-connector/m2c2-opcda-connector/m2c2-opcda-connector.py#L26

This module is unused. Looks like we could remove Pyro3 @georgebearden

**Comment by tomnight** [comment]
Thanks for the feedback we will address this in the next release

**Comment by emcfins** [comment]
We have released v2.2.0 of the solution which now uses Pyro4 and includes the OpenOPC library that supports Python3.
You can find the landing page for the latest version of the solution [here](https://aws.amazon.com/solutions/implementations/machine-to-cloud-connectivity-framework/).
