### ISSUE TITLE
m2c2_osipi_connector - dependency issues

### ISSUE THREAD

**Issue by andormarkus** [aws-solutions/machine-to-cloud-connectivity-framework#21]
Hi AWS Team,

I have checked the `requirements.txt` of the `m2c2_osipi_connector` and it uses unverified, not official, unmaintained dependency:
 - https://github.com/dcbark01/PI-Web-API-Client-Python.git

I have checked this [dependency](https://github.com/dcbark01/PI-Web-API-Client-Python.git) and it looks like an unofficial fork of the `osisoft.pidevclub.piwebapi`. We got the following concerns using this dependency:
 - unmaintained  - no commit or release more than 5 years
 - uses old API specification - PI Web API 2017
 - unclear licensing  - it has Apache-2.0 license, without knowing the licence original repo it is very dangerous to use it.

Please, can you check inside AWS what is a verified solution to load data from OSI PI to AWS?

Thanks,
Andor

**Comment by amohames** [comment]
Hi Andor
Let me look into this issue for you.

Thanks
Saif

**Comment by amohames** [comment]
Hi Andor, We are planning to remove the unsupported lib from the code in the next release. I will update the ticket when I have more details.

Thanks
Saif
