### ISSUE TITLE
NameError: name 'resource' is not defined

### ISSUE THREAD

**Issue by wchaws** [aws-solutions/machine-to-cloud-connectivity-framework#3]
The `resource` variable is not defined 

https://github.com/awslabs/machine-to-cloud-connectivity-framework/blob/5daf5f750bfa1d95cc3200476bd3230cb0df2c2a/deployment/machine-to-cloud-connectivity-framework.template#L709

**Comment by tomnight** [comment]
Thanks for the feedback, this is a bug and will cause a stack delete to fail. We will get this fixed in the next release.

**Comment by emcfins** [comment]
This has been resolved in the v2.1.0 and v2.2.0 releases
