### ISSUE TITLE
Can I get the total cost for this setup?

### ISSUE THREAD

**Issue by chougule07** [aws-solutions/machine-to-cloud-connectivity-framework#6]
Can I get the total cost for this setup? You can provide the AWS Calculator link for this.

**Comment by emcfins** [comment]
Thank you for opening this issue. We'll look into how to address this in the next update.

**Comment by emcfins** [comment]
We released an update to the solution and have included the cost estimation for the latest version in the implementation guide.
You can find the cost breakdown [here](https://docs.aws.amazon.com/solutions/latest/machine-to-cloud-connectivity-framework/overview.html#cost).
