### ISSUE TITLE
Latency Benchmarking

### ISSUE THREAD

**Issue by xsahban** [aws-solutions/machine-to-cloud-connectivity-framework#9]
**What is your question?**

I want to understand if there is any benchmarking done on the latency perspective with this framework.

**Comment by beomseoklee** [comment]
@xsahban Unfortunately, we don't have benchmarking result regarding the solution. We will add that to our backlog item so that we can provide some meaningful benchmarking result in the future.

By the way, which latency are you looking for? The latency between your machine and Greengrass?

**Comment by xsahban** [comment]
Hi @beomseoklee, Thanks for the reply.

In a top-level sense, I want to know the Overall latency, from the event-occurrence-time to the cloud-ingestion time, with the factors and/or configurations that will affect the latency.

In-depth, I want to understand the latency being added in each hop, from OPC-UA to Stream Manager's Stream, and from there to Kinesis Data Stream.

**Comment by wsmatth** [comment]
@xsahban I have found that the latency between the greengrass device and iot core is the largest bottleneck.  This is fully depending on the internet connectivity and distance from the IoT Core region.  
The rest of the latency is in the order of a few milliseconds worth in my experience using greengrass streams and kinesis

**Comment by mttwise** [comment]
@xsahban I have found that the latency between the greengrass device and iot core is the largest bottleneck. This is fully depending on the internet connectivity and distance from the IoT Core region.
The rest of the latency is in the order of a few milliseconds worth in my experience using greengrass streams and kinesis
